sudo: required
language: cpp
compiler:
  - gcc
jobs:
  include:
    - stage: Unpacker_v2
    script:
        - wget https://root.cern.ch/download/root_v6.12.06.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
        - gunzip root_v6.12.06.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
        - tar xvf root_v6.12.06.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
        - source root/env/thisroot.sh
        - Tests/Unpacker/testUnpacker.sh
    script:
    - stage: Unpacker
      script:
        - Tests/Env/testSetupCpuEnv.sh
        - Tests/Unpacker/testUnpacker.sh
    - stage: EnvCPU
      script: 
        - Tests/Env/testSetupCpuEnv.sh
        - Tests/Ops/buildOps.sh
        - Tests/Training/Training.sh
    - stage: EnvFull
      script: Tests/Env/testSetupFullEnv.sh
notifications:
  email:
    recipients:
        #- vilius.cepaitis@cern.ch
        #- mkomm@cern.ch
    on_success: change
    on_failure: always


