sudo: required
language: cpp
compiler:
  - gcc
jobs:
  include:
    - stage: EnvFull
      script: Tests/Env/testSetupFullEnv.sh
    - stage: EnvCPU, Unpacker and Training check
      script:
        - Tests/Env/testSetupCpuEnv.sh
        - Tests/Ops/buildOps.sh
        - Tests/Training/Training.sh
        - Tests/Unpacker/testUnpacker.sh
notifications:
  email:
    recipients:
        - vilius.cepaitis@cern.ch
        - mkomm@cern.ch
    on_success: change
    on_failure: always


