sudo: required
language: cpp
compiler:
  - gcc
jobs:
  include:
    - stage: EnvCPU, Unpacker and Training check
      script:
        - Tests/Env/testSetupEnv.sh
        - Tests/Ops/buildOps.sh
notifications:
  email:
    recipients:
        - vilius.cepaitis@cern.ch
        - mkomm@cern.ch
    on_success: change
    on_failure: always


