name: tf_cpu
channels:
 - conda-forge
 - quantstack
dependencies:
 - conda-forge::root==6.16
 - pypi::pyyaml==3.12
 - pypi::h5py==2.7.1
 - pypi::Keras==2.1.5
 - pypi::scipy==1.0.0
 - conda-forge::scikit-learn==0.20.0
 - pypi::matplotlib==2.2.4
 - pypi::pydot==1.2.4
 - pypi::tensorflow==1.6.0
