name: tf_cpu
channels:
 - conda-forge
 - quantstack
dependencies:
 - root=6.18.00
 - pyyaml==3.12
 - h5py==2.7.1
 - Keras==2.1.5
 - scipy==1.0.0
 - scikit-learn==0.20.0
 - matplotlib==3.1.1
 - pydot==1.2.4
 - tensorflow==1.6.0
