name: tf_cpu
channels:
 - conda-forge
dependencies:
 - cmake==3.15
 - python==2.7.15
 - root==6.18.04
 - numpy==1.16.5
 - uproot==3.11.1
 - h5py==2.10.0
 - scipy==1.2.1
 - scikit-learn==0.20.4
 - matplotlib==2.2.4
 - tensorflow==1.6
 - keras==2.1.5

