name: tf_gpu
channels:
 - conda-forge
dependencies:
 - root=6.14.06
 - pyyaml==3.12
 - h5py==2.7.1
 - Keras==2.1.5
 - scipy==1.0.0
 - scikit-learn==0.20.0
 - matplotlib==2.0.0
 - pydot==1.2.4
 - tensorflow-gpu==1.6.0
 - gpustat==0.4.1
 - setGPU==0.0.7
 
