name: tf_gpu
dependencies:
 - pypi::pyyaml==3.12
 - pypi::h5py==2.7.1
 - pypi::scipy==1.0.0
 - pypi::sklearn
 - pypi::matplotlib==2.2.4
 - pypi::pydot==1.2.4
 - pypi::tensorflow-gpu==1.6.0
 - pypi::gpustat==0.4.1
 - pypi::setGPU==0.0.7
 - pkgs/main::Keras==2.1.5
 
