name: tf_cpu
channels:
 - conda-forge
dependencies:
 - python==2
 - root==6.16
 - pyyaml==3.12
 - h5py==2.7.1
 - scipy==1.0.0
 - scikit-learn==0.20.0
 - matplotlib==2.2.4
 - pydot==1.2.4
 - tensorflow==1.6.0
 - Keras==2.1.6

